### ISSUE TITLE
Support for logging, graphql-shield, and a real-world example

### ISSUE THREAD

**Issue by ramandhingra** [cerino-ligutom/GraphQL-Starter#12]
Hi

This is a very wonderful boilerplate I have come across so far.

It'd be great if you can add the following support to this..
a. logging
b. Authorization using graphql-shield
c. A real world example for example Post and Comment.

Thank you for your contributions to the community.

**Comment by cerino-ligutom** [comment]
Hello, thank you for opening this issue and the feedback. Happy to hear that.

For point `c`, I didn't really think there's a need for this but I do see your point. It could elaborate more on how to use this boilerplate further but at the same time I don't want to make assumptions on the entities either. I think I wanted to reduce the amount of files around so that those who use this boilerplate can get started right away with what they want to do without touching anything else aside from some metadata such as the `package.json` name and license stuffs. You can probably imagine how it'd go. Say we support full CRUD (w/ pagination) for both _Post_ and _Comment_ entities. That would then be 10 basic use cases multiplied by 2 for both REST controllers and GraphQL resolvers. Not to mention, the dataloaders, express routes, migration files and other auxiliary files. You could argue, one could easily delete the module folder and deregistering the express routers on `app.ts` but I'd like to hear from you though, were there some things that are confusing that could be addressed by adding a real world example?

I did implement points `a` (logging with [morgan](https://www.npmjs.com/package/morgan) + [winston](https://www.npmjs.com/package/winston)) and `b` (graphql-shield) previously before the big refactoring last week. You can trace that back that in the commits if you want to see an example. 

However, I decided to remove them along with the refactoring and left that concern to the users of this template on how they want to do their authN/authZ and logging needs since from what I've learned so far, it really varies from project to project and it's a very huge topic in and of itself.

This might get long a bit but let me try to explain why I removed `a` and `b`.

> a. logging

There are just simply too many ways of doing this and I think an organization or team will, most likely, have their own ways and set of tools to achieve this. Take for example, one could use Splunk for very advanced use cases. If you only have a single instance on a VPS, then morgan + winston, or [pino](https://github.com/pinojs/pino) could be a good idea where the rotating logs could be written alongside the server. If you have multiple then you could configure both to centralize and stream the logs somewhere else. On the other hand, instead of unifying the logs, you could have a reverse proxy server (say nginx) in front of your application server and log the network logs from there then have an entirely different logger for the application itself. If you deploy on AWS or Heroku, you could utilize their logger as well. There's just too many ways imo and I think such concern should be left to how you guys want to handle it. 

> b. Authorization using graphql-shield

Yes. Good suggestion. As I mentioned above, I did implement this before but decided to remove it for 2 reasons:

## Reason 1: Duplication of business rules

Say you need to support both a REST and GraphQL interface for your API (yes, this can happen, at least it happened to me on one project and I realized something along the way, more on that on reason 2), how would you like to handle the implementation details of your authN/authZ? Duplicate on both? Maybe make an adapter or facade for each (controller/resolver) to your auth logic? Centralize it somewhere? Or maybe something else entirely.

In the case of this boilerplate, I decided to centralize it somewhere, in the _use case_ to be exact as seen on this [example](https://github.com/cerino-ligutom/GraphQL-Starter/blob/2b7f7b456ac7f8e0f97350bf72f53c10852d18c6/src/modules/user/use-cases/get-users.use-case.ts#L26). There you can see that the _use case_ now has a normalized _context_ (see `IContext`) where both the resolver and controller must supply. 

![image](https://user-images.githubusercontent.com/6721822/109524720-cbcc5000-7aeb-11eb-97ff-403984daf31c.png)

This way, they funnel in to our business logic layer and keep the interface layer thin. I also coded it in such a way that you can easily refactor this by, say for instance, removing the _context_ from the _use cases_ and handle it somewhere else like on your controllers/resolvers or graphql-shield if you prefer. Then again, if you do that, we'd get back to the "issue" of how would you handle the authN/authZ for your REST endpoints. Worst-case, you'd end up needing to duplicate business rules which is error-prone.

## Reason 2: Got convinced by a great book since I experienced the pain points that was pointed out

Related above, as you can see, "maintainability" kind of suffers but that's a tradeoff one has to make whether it's good enough for your project's needs or not. If you have a pure GraphQL API, then graphql-shield will simplify things by having a dedicated layer for auth and even do schema validation as well on the same layer but just make sure to know what you're trading off when you introduce that layer.

Been researching a lot about the topic for a long time but nothing really sat well with me until I read this [book](https://book.productionreadygraphql.com/) by Marc-Andre which I highly recommend. He provides great insights about authN/authZ as well. Let me quote a few things from the book that hit hard with my experiences and why I decided to remove it on this boilerplate:

### For authentication: 

> I strongly recommend leaving authentication concerns out of the GraphQL schema, and simply expect a currentUser or other session concepts to be present in the GraphQL context when executing a query. Resolvers should not be aware of HTTP headers or tokens. This way we can swap out, or support many different authentication schemes without changing the schema. It also makes the schema much easier to interact with, and more stateless.

To give you an example from experience, SSO (login with Facebook, GitHub, Google, etc.)  needs came, it became problematic and you can probably imagine if you're familiar with how OIDC/OAuth works. That's something I've learned the hard way. So I applied what I think could be a good solution around it to this boilerplate. As you can see, the `login` mechanism is on a REST endpoint, and the checking of authN is on the _use case_.

### For authorization:

> You want GraphQL to rely as much as possible on the authorization you already have deeper in your application. The main reason we want to avoid having all authorization logic at the GraphQL level is that GraphQL is often just one possible way to access your domain logic. If we start implementing everything in our GraphQL layer, we’re now in a situation where we have to make sure to copy these business rules everywhere else and maintain them while they evolve, which is very error-prone.

I agree a lot with this. And without graphql-shield, authZ could then live somewhere else deeper in your app. Could be on your domain models if you do _DDD_ or _use cases_ for this boilerplate.

That's what I think and why interface layers should really be thin. Move the important stuffs one level down or deeper in your application. If you don't like calling the [checkAuthentication()](https://github.com/cerino-ligutom/GraphQL-Starter/blob/2b7f7b456ac7f8e0f97350bf72f53c10852d18c6/src/modules/user/use-cases/get-users.use-case.ts#L26) function within your use cases, you could write a higher order function instead and wrap your use cases with it.

I hope that explains why I removed `a` and `b` and why I didn't expand much on `c`.

**Comment by cerino-ligutom** [comment]
There's also [this](https://github.com/maticzav/graphql-shield/issues/352) and [this](https://github.com/maticzav/graphql-shield/issues/466). I did [attempt to get intellisense](https://github.com/cerino-ligutom/GraphQL-Starter/blob/f37e2d519f42869fa663a783efac89d69cba4ea7/src/graphql-shield/index.ts#L68) out of it, and while it works for the root stuffs, it was still a hotspot.

**Comment by ramandhingra** [comment]
Real-world example: The only reason that it should be there is that it should educate a novice programmer how to make use of the underlying features (not all, only important/advanced) provided by this boilerplate. You are right, if you add this module to the code, it won't be be an ideal boilerplate anymore. If you have time and if you think it is really necessary to have one, you may do it in another repository.

According to my viewpoint, if boilerplate becomes opinionated to some extent, it is not an issue. For example, it is very easy to implement a winston logger middleware.. and not difficult to  remove those lines of code where it is called.

The explanation given by you regarding Authorization / Authentication is very nice. I learned new things. Implementing both AuthN/AuthZ for GraphQL  and REST endpoints is certainly not easy. So let the users of this code decide whatever suits them, if they need to implement graphql-shield, let them do themselves.

I have a question.. would you pl. answer? How about creating the Permissions model/entity and associate the different permissions with different roles and assign a role to a user. In this case, we don't need to worry about graphql-shield or implementing auth for both REST and GraphQL, etc. What is your viewpoint? If I do so, what change(s) do I need to implement in your existing code?

I observed one thing in the Users model. You are storing both password hash and salt. If we are using bcrypt, its advantage is ... Instead of storing the salt in a dedicated column, it is directly stored in the final hash. So just store a simple hashed password is probably sufficeint.

Thanks for your detailed explanation.

**Comment by ramandhingra** [comment]
An important use case regarding the logging .. The internal database, GraphQL, web server errors / codes should not be propagated to the UI layer and should be logged instead. Let the other errors be sent further.

**Comment by cerino-ligutom** [comment]
> Real-world example: The only reason that it should be there is that it will educate a novice programmer how to make use of the underlying features (not all, only important/advanced) provided by this boilerplate.

I added the [recommended workflow section](https://github.com/cerino-ligutom/GraphQL-Starter#recommended-workflow) to shed some light on that but yep, if one skims throughout the code right away, it could be confusing on how to do things.

> According to my viewpoint, if boilerplate becomes opinionated to some extent, it is not an issue. For example, it is very easy to implement a winston logger middleware.. and not difficult (if one wants to) to remove those lines of code where it is called.

True, but if you think about it, since it's pretty easy to do this and varies from project to project, that's why I simply omitted it and leave that to the developer's discretion 🙂 

> I have a question.. could you pl. answer? How about creating the Permissions model/entity and associate the different permissions with different roles and assign a role to a user. In this case, we don't need to worry about graphql-shield or implementing authorization for both REST and GraphQL, etc. What is your viewpoint? If I do so, what change(s) do I need to make in your existing code?

That's a very loaded question and a huge topic in itself. I recommend reading about RBAC/ABAC and get the concepts down. The boilerplate already has system roles in place so what's left is the implementation details for the authorization. I intentionally omitted that as there's so many ways to go about it. But as I [mentioned](https://github.com/cerino-ligutom/GraphQL-Starter#important-notes) in the readme, I recommend using [CASL.js](https://casl.js.org) for this. The cookbook has what you're asking for. In any case, here's a direct [link](https://casl.js.org/v5/en/cookbook/roles-with-static-permissions).

> I observed one thing in the Users model. You are storing both password hash and salt. If we are using bcrypt, its advantage is ... Instead of storing the salt in a dedicated column, it is directly stored in the final hash. So just store a simple hashed password is probably sufficient.

You're right, the dedicated salt is redundant particularly with `bcrypt`. I'll refactor it later. Thanks for the heads up.

> Great if you can add Jest support..

Yep, haven't found the time to do it yet. You're welcome to open a PR if you'd like.

> An important use case regarding the logging .. The internal database, GraphQL, web server errors / codes should not be propagated to the UI layer and should be logged instead. Let the other errors be sent further.

Errors are actually obscured [here](https://github.com/cerino-ligutom/GraphQL-Starter/blob/8fa32b5902fd3937dc7a25350fdb77a33019e405/src/errors/error-handler/index.ts#L53) during production mode. Which is then normalized as a response [here](https://github.com/cerino-ligutom/GraphQL-Starter/blob/8fa32b5902fd3937dc7a25350fdb77a33019e405/src/middlewares/error.middleware.ts#L12) for REST API calls and [here](https://github.com/cerino-ligutom/GraphQL-Starter/blob/8fa32b5902fd3937dc7a25350fdb77a33019e405/src/graphql/index.ts#L54) for GraphQL API calls.

As for logging errors, you really have the freedom to choose your strategy. Could be on the error handler, [base error](https://github.com/cerino-ligutom/GraphQL-Starter/blob/8fa32b5902fd3937dc7a25350fdb77a33019e405/src/errors/base.error.ts#L33), the custom internal server error when all else fails, just on a specific error as needed, anything goes really.

But yes, I do agree that's an important use case for logging which is to have visibility for errors, again imo, from what I've seen, it typically varies from project to project and I didn't want to impose any opinions here as it would most likely get scratched and replaced by the developer's preferences.

Hope that answers your concerns.

**Comment by ramandhingra** [comment]
Thanks. Answers are pretty satisfactory.

One more point.. Kindly add logout handler / use case.

**Comment by cerino-ligutom** [comment]
> Thanks. Answers are pretty satisfactory.

Awesome.

> One clarification. If I add CASL authorization support, I do not need to do any changes in your code. Am I right?

There shouldn't be any changes as I'd imagine, you'll just be adding code.

> One more point.. Kindly add logout handler / use case.

Haha. I also intentionally left that out as invalidating/revoking JWTs is a huge topic and I decided to leave that concern to the developers since there are plenty of ways to go about it. 🙂

Just to give you some ideas to ponder on as to why:

- How do you exactly invalidate a JWT when it only expires until the computed datetime? 
- Would you keep a blacklist for the access tokens on your database? 
- If yes above, then why not just use session cookies at this point? Probably CORS? Or your users don't want to turn on cookies?
- Should you introduce a long-lived refresh token and short-lived access tokens?
- What if the refresh token is compromised thru XSS?
- Should you then put your JWT within a secure `httponly` cookie?
- What's the point of the token at that point then? Maybe might as well use session cookies?
- Should you use a time-based approach? Where you keep track of when the user last logged out and any token generated prior to the said that is considered invalid?
- What if you need to support sessions for multiple devices?

And so on and so forth. It's a different rabbit hole and an entirely different topic 🙂 Regardless, if your app isn't really mission critical, is very simple, or have mitigations for XSS via well-defined CSP rules, just simply deleting the token on the front-end should suffice. But again, I recommend reading more into this topic and come up with a strategy on invalidating your tokens or just switch entirely to session cookies which is fairly easy to implement.

I'll close this issue now. Thanks for the inputs and feedback!

**Comment by cerino-ligutom** [comment]
Hello @ramandhingra , thought I'll update you here. Delegated the session management to [SuperTokens](https://supertokens.io/). The latest setup now has a logout handler and use case.

**Comment by ramandhingra** [comment]
Hello @cerino-ligutom 

I am glad to hear about it. I'll look at the source code and discuss about it soon.

**Comment by ramandhingra** [comment]
Hello

The Super Tokens portion of the code looks very well organized and it's been updated regularly.

I just have one question. There is another very popular open source named Keycloak that does the same what Super Tokens is doing. Keycloak is backed by a strong community, people are using it in production environment. It definitely outsmarts Super Tokens.. number of github stars, no. of forks, regular commits, etc.

To be honest, I'd prefer keycloak. :)

Pl. keep in touch. I'd like to hear from you.

**Comment by cerino-ligutom** [comment]
I've evaluated the majority of IAM Providers out there to see for myself including Keycloak and of course, assess whether SuperTokens' claim is true since it's a relatively new player.

![image](https://user-images.githubusercontent.com/6721822/116777267-455acd00-aaa0-11eb-89db-c8b16258c173.png)

> Keycloak is backed by a strong community, people are using it in production environment.

There are companies that use SuperTokens in a production environment as well. I plan to use it on future projects also 🙂 Seeing that SuperTokens is backed by Y Combinator gives me some peace of mind that they're going to see it through. Here's a [great talk](https://www.youtube.com/watch?v=6Vzit514kZY&list=PLE5w09cAseKTIFCImkqFbSeYMHPzW7M_f) by the author of SuperTokens.

> It definitely outsmarts Super Tokens.. number of github stars, no. of forks, regular commits, etc.

It'd be an unfair comparison when the repo just started on the 1st week of January 2020 (it's pretty young) so I would look beyond that aside from the few metrics you mentioned. Won't go over them individually as it's been a long research and handling security is seriously arduous. But ultimately, I opted for a solution that does a good job at solving the problem with an approach that one can believe in, doesn't require unnecessary huge cognitive overhead to the developers, first-party (free) dedicated support in case you have any concerns and the customizability of the UI + Auth Flow is really good as they claim.

By the end of the day, they solve the same problem. If you need out-of-the-box solutions and/or the bells and whistles of other existing solutions that SuperTokens doesn't provide yet, then go for that. Give it some time and SuperTokens will eventually catch up in terms of features. For now, I'd like to see how SuperTokens will turn out moving forward as it looks promising and it does solve a problem I have with this boilerplate so I have no qualms with it.

**Comment by ramandhingra** [comment]
Your answer is quite satisfactory. And also you are using only the Session Management feature of Super Token. So it is perfectly ok to stick to it. 

I an sure the person who is heading Super Tokens has excellent knowledge about this subject. 

Following lines taken from ... https://blitzjs.com/docs/auth
The session management follows the same approach as the state of the art SuperTokens library. The CTO of SuperTokens, Rishabh Poddar, designed and oversaw our implementation. We're extremely grateful for Rishabh's help! 🙏

Do you have any plans to add the CASL ability to your boilerplate?

**Comment by cerino-ligutom** [comment]
> Do you have any plans to add the CASL ability to your boilerplate?

I do actually, the CASL API seems to have stabilized now. The only reason I removed it before was because the TS types are really tricky to extend back then which got annoying to some extent but feature-wise once you sort that out, it's a breeze and superb. Will update again here once I decide on an approach since I'm also considering to use this [lib](https://github.com/stalniy/ucast/tree/master/packages/sql) along with it.
