### ISSUE TITLE
Knex built in timestamps method

### ISSUE THREAD

**Issue by apackin** [cerino-ligutom/GraphQL-Starter#21]
Hi @cerino-ligutom, thanks for sharing this great boiler plate!

I noticed you're using a custom `addTimeStamps` helper to add `created_at` and `updated_at` columns to your tables.
Knex actually has a built in [table.timestamps](https://knexjs.org/#Schema-timestamps) method. Are you using your custom method to gain that extra precision?

How would you feel about a PR that switched to use that method?

Example:
```
    await knex.schema.createTable(TABLE_NAME, (t) => {
      t.uuid('id').primary();
      t.string('firstName').notNullable();
      t.string('middleName');
      t.string('lastName').notNullable();
      t.string('email').unique().notNullable();
      t.string('hash').notNullable();
    });
    await addTimeStamps(knex, TABLE_NAME, {
      createdAt: true,
      updatedAt: true,
    });
  }
  ```
  
becomes:
  ```
    await knex.schema.createTable(TABLE_NAME, (t) => {
      t.uuid('id').primary();
      t.string('firstName').notNullable();
      t.string('middleName');
      t.string('lastName').notNullable();
      t.string('email').unique().notNullable();
      t.string('hash').notNullable();
      t.timestamps(false, true)
    });
  }
  ```

**Comment by cerino-ligutom** [comment]
Hello @apackin! Thanks for checking out this boilerplate 🎉 

Yes, I'm aware of `knex.timestamps` but I stopped using it due to how easy it is to shoot yourself in the foot (it happened to one of my projects and learned from there) when working with Date objects on JavaScript and I hope [Temporal](https://github.com/tc39/proposal-temporal) supports precision that's more than 3 once that finalizes.

## Short Explanation for that helper function:

**Reason 1**: 
`knex.timestamps` doesn't allow setting the precision and can be problematic with JS Date objects.

**Reason 2**: 
I want a centralized way to deal with timestamps where the API is clear and certain details are abstracted such as the precision (see long explanation) and field name casing as it's very easy to miss the 3rd parameter in `knex.timestamps` if you don't use the other signature (pass an object).

I wait for the day it accepts a precision parameter so we can do something like this 😄 

```js
t.timestamps({
  useTimestamps: true,
  defaultToNow: true,
  useCamelCase: true,
  precision: 3, // this
});
```

But even then, I'd rather hide those details which is the existing helper you see right now.

```js
addTimeStamps(knexInstance, tableName, { createdAt: true, updatedAt: true });
```

## Long Explanation for Reason 1:
JavaScript's Date precision is at most 3 **but the database default may vary**. 

![image](https://user-images.githubusercontent.com/6721822/151493432-4f252664-1c1f-4a7a-a177-c3c084d9d7c6.png)

In the case of PostgreSQL, it stores timestamps at the maximum possible precision which is 6 if not set.

**Code:**
```js
t.timestamps(false, true);
```
**Result:**
![image](https://user-images.githubusercontent.com/6721822/151493568-1bd93374-c363-46cc-b412-037f16144f89.png)

`knex.timestamps` **doesn't allow setting the precision**, at least none that I'm aware of, and since it defaults to a precision of 6 in postgres, you can probably imagine there'd be missed records if you do paginations against dates where the milliseconds are very close and pass a JavaScript Date object on the `where()` bindings.

You can get away with this issue if you just purely pass strings around your app but when you start doing computations with it, you'll go back to dealing with JS Date objects (back to 3 precision). That, or use a different solution that can preserve precisions greater than 3.

![image](https://user-images.githubusercontent.com/6721822/151494060-8ef146b9-f4ff-4fd4-8471-34c26cd6a4d8.png)

To name a few common areas where you can easily shoot yourself in the foot:
- When fetching timestamp/datetime fields from the database using Knex, Knex deserializes the timestamp/datetime string into a JS Date object (back to 3 precision).
- When clients pass a datetime string to the GraphQL API, GraphQL Date Scalars converts valid ISO 8601 string back to JS Date objects (back to 3 precision)
- If your validation library validates date fields then outputs a JS Date object instead of the original string passed.

And the list goes on...

**Comment by apackin** [comment]
Makes sense. Thank you so much for the quick and thoughtful reply.

IDK if Knex is actually working on adding `precision` to `table.timestamps`. I'll open up the issue there if I get a chance.
Seems dangerous that a JS library defaults to set the DB timestamps to not match the JS timestamps.
