### ISSUE TITLE
How to use migrate:latest

### ISSUE THREAD

**Issue by alaamh** [cerino-ligutom/GraphQL-Starter#26]
Thank you for the wonderful boilerplate, Amazing work.

I would like run the migrate/seed the existing `src/db/migrations` but unfortunately getting the below error, I have followed the steps and running all on the docker.  

`
npm run migrate:latest

> graphql-starter@ migrate:latest 
> knex --knexfile ./knexfile.* migrate:latest

Requiring external module ts-node/register
getaddrinfo ENOTFOUND db
Error: getaddrinfo ENOTFOUND db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26)
`

**Comment by alaamh** [comment]
Hi again,

I'm not sure if I did it right, I have change host name from db to localhost in the .env to use below connection string:
`POSTGRES_CONNECTION_URL=postgresql://postgres:password@localhost:5432/db`

it works, and I can see the new users table has been created, but for seeding:
```
npm run seed          

> graphql-starter@ seed /
> knex --knexfile ./knexfile.* seed:run

Requiring external module ts-node/register
Error while executing "src/db/seeds/001-seed-superadmin.ts" seed: insert into "users" ("email", "firstName", "hash", "lastName") values ($1, $2, $3, $4) ON CONFLICT DO NOTHING RETURNING id - null value in column "id" of relation "users" violates not-null constraint
Error: Error while executing "src/db/seeds/001-seed-superadmin.ts" seed: insert into "users" ("email", "firstName", "hash", "lastName") values ($1, $2, $3, $4) ON CONFLICT DO NOTHING RETURNING id - null value in column "id" of relation "users" violates not-null constraint
    at Seeder._waterfallBatch (/node_modules/knex/lib/migrations/seed/Seeder.js:118:23)
error: insert into "users" ("email", "firstName", "hash", "lastName") values ($1, $2, $3, $4) ON CONFLICT DO NOTHING RETURNING id - null value in column "id" of relation "users" violates not-null constraint
    at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

**Comment by alaamh** [comment]
So I have update the `001-seed-superadmin.ts` in `superadmin.set` added the following line:
`id: 'ea5d346a-12eb-4ee0-91fa-5fd8d4ccd404',`

Sorry for bothering you :)

**Comment by cerino-ligutom** [comment]
Hello @alaamh ,

Thanks for checking out this boilerplate! I should document this part.

If you're using Docker and started this boilerplate with `docker-compose up`, you actually need to get inside the container and run the command from there.

![image](https://user-images.githubusercontent.com/6721822/158017391-113ff2c3-080b-442e-8f2e-346bedac0fbf.png)

Otherwise, if you're running the app standalone directly on your host, you'll have to configure the endpoints yourself 🙂

**Comment by cerino-ligutom** [comment]
> So I have update the `001-seed-superadmin.ts` in `superadmin.set` added the following line: `id: 'ea5d346a-12eb-4ee0-91fa-5fd8d4ccd404',`
> 
> Sorry for bothering you :)

Will make a PR to fix this. Originally, the database was generating the ID but I decided to [move it on the application level](https://github.com/cerino-ligutom/GraphQL-Starter/blob/f90c101bf8c9050d4ff248936f5a977187540fc5/src/db/models/common/base-model.ts#L14) but these [Objection Hooks](https://vincit.github.io/objection.js/guide/hooks.html) do not fire currently on the seed scripts since we're not using the Objection Model to do the insertion.

**Comment by cerino-ligutom** [comment]
@alaamh addressed the seeding issue w/ this PR https://github.com/cerino-ligutom/GraphQL-Starter/pull/29

Can you try pulling from the `main` branch again and see if it solves your issue?

**Comment by alaamh** [comment]
Sure, thanks

**Comment by alaamh** [comment]
confirm, it fixed.
