### ISSUE TITLE
GraphQL ICursorResult (not a bug)

### ISSUE THREAD

**Issue by alaamh** [cerino-ligutom/GraphQL-Starter#33]
Hi @cerino-ligutom Thanks again for your help and support.

I struggle to return results without paging, let's assume we would like to return all roles without paging, can you please share an example? should we create a new interface `ICursorResult` or just `IResults `?

**Comment by cerino-ligutom** [comment]
Hello @alaamh , since you don't need pagination, then it doesn't make sense to use any of the cursor pagination stuffs. Which means you only need to work with the ORM (ObjectionJS in this case) so just fetch everything from the database.

You could use [`select()`](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#select) on your Objection model. 

```ts
const results = await RoleModel.query().select(); // Where RoleModel is your Objection Model

console.log(results); // You should get an array of RoleModel Objection instances
```

**Comment by alaamh** [comment]
I will try this thank you for your help.
