### ISSUE TITLE
micro-services integration approach 

### ISSUE THREAD

**Issue by alaamh** [cerino-ligutom/GraphQL-Starter#36]
Thank you again for your usual help and support. we always looking to get expert advice like you to confirm the design approach. 

let's say we have two running micro-services communicate with this template as the main micro-service, the authentication happens on the main one which is this template then it will prepare the userid with other things then pass it to the micro-service through an internal HTTP call or should we use a service bus or a library? 

I'm worried about the response time, for example, assume one of the micro-service is for reference data management which supposes to return the categories if we use a queue the response will not be easy to merge with the main response from the main service. what is your advice?

**Comment by cerino-ligutom** [comment]
Hello @alaamh, I'm afraid there are plenty of ways to go about this and there's no silver bullet that I can advise so you'll have to make an educated decision what's best based on the scope and acceptable tradeoffs for your architecture. 

Try looking into GraphQL Federation and see if it addresses your concerns and give you ideas from there to achieve your goal with the help of GraphQL. Since this template is using Apollo, you'd want to check [Apollo Federation](https://www.apollographql.com/docs/federation/) for implementation details.
